# 아이리스 품종 실습

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 1.과거의 데이터를 준비합니다.

In [2]:
  파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

종속변수는 품종입니다. 품종은 범주형 데이터입니다.

In [3]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [4]:
print(아이리스)

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]


다음과 같이 종속 데이터가 원핫인코딩으로 변경됨을 확인하였습니다.

## 2. 모델의 구조를 만듭니다

In [5]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

## 3.데이터로 모델을 학습(FIT)합니다.

In [6]:
model.fit(독립, 종속, epochs=1000, verbose=0)

In [7]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1679 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1679 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1677 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1675 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1672 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1671 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1668 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1671 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1670 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1669 - accuracy: 0.9733


정확도가 97%까지 나왔습니다.

## 4. 모델을 이용합니다

In [8]:
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9913836e-01 8.6145685e-04 6.1887718e-08]
 [9.9694175e-01 3.0575895e-03 6.5024477e-07]
 [9.9833786e-01 1.6618934e-03 2.1840840e-07]
 [9.9565506e-01 4.3439572e-03 9.0796527e-07]
 [9.9925119e-01 7.4879965e-04 4.4815788e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [9]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[4.84026316e-07 1.16601974e-01 8.83397579e-01]
 [1.15586192e-06 1.56181514e-01 8.43817294e-01]
 [2.34414279e-06 2.41597950e-01 7.58399725e-01]
 [6.05719094e-07 1.74887046e-01 8.25112343e-01]
 [5.93987534e-06 3.64638597e-01 6.35355413e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


실제 데이터와 비교해보면 모델이 정답을 잘 맞추고 있습니다!

In [10]:
###########################
# weights & bias 출력
print(model.get_weights())

[array([[ 0.9458694 ,  0.13497388, -0.11107181],
       [ 3.5183952 ,  1.3048372 , -0.7672846 ],
       [-3.3322797 , -0.0269182 ,  1.1340564 ],
       [-4.209855  , -0.83916837,  2.2617729 ]], dtype=float32), array([ 1.9511682,  1.4765203, -1.8028318], dtype=float32)]
