# 아이리스 품종 실습

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 1.과거의 데이터를 준비합니다.

In [2]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

종속변수는 품종입니다. 품종은 범주형 데이터입니다.

In [3]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [4]:
print(아이리스)

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]


다음과 같이 종속 데이터가 원핫인코딩으로 변경됨을 확인하였습니다.

## 2. 모델의 구조를 만듭니다

In [5]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

이번엔 히든레이어를 여러개 쌓아보겠습니다.

## 3.데이터로 모델을 학습(FIT)합니다.

In [6]:
model.fit(독립, 종속, epochs=1000, verbose=0)

In [7]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0559 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0464 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0491 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0464 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0466 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0477 - accuracy: 0.9933
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0481 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0483 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0471 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0529 - accuracy: 0.9800


정확도가 98%까지 나왔습니다.

## 4. 모델을 이용합니다

In [8]:
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9999988e-01 1.0937573e-07 4.8799831e-12]
 [9.9999988e-01 1.7196261e-07 1.5493062e-11]
 [9.9999964e-01 3.2915122e-07 3.1123725e-11]
 [9.9999976e-01 2.6281745e-07 3.2476348e-11]
 [9.9999988e-01 1.3285768e-07 6.1585186e-12]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [9]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[3.0965802e-18 2.1327874e-03 9.9786723e-01]
 [7.9695656e-17 1.4168782e-02 9.8583120e-01]
 [5.3664282e-17 1.3538247e-02 9.8646170e-01]
 [8.3263949e-19 7.3766889e-04 9.9926227e-01]
 [2.7767551e-16 2.5259336e-02 9.7474062e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


실제 데이터와 비교해보면 모델이 정답을 잘 맞추고 있습니다!